server:
    port: 8085
    servlet:
      context-path: /factory
      session:
        timeout: 36000 #10小时超时间
    tomcat: 
      uri-encoding: UTF-8
      max-threads: 1000
      min-spare-threads: 30

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.104.252.174:3306/erma?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    #初始化大小，最大，最小
    initialSize: 5
    minIdle: 10
    maxActive: 50
    #配置获取连接等待超时的时间
    maxWait: 60000
    #配置一个连接在池中最小生存的时间，单位是毫秒
    validationQuery: SELECT 1 FROM DUAL
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    minEvictableIdleTimeMillis: 25200000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    removeAbandoned: true
    removeAbandonedTimeout: 1800
    #打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    logAbandoned: true
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录 
    connectionProperties: druid.stat.mergeSql=true

  thymeleaf:
    encoding: UTF-8
    suffix: .html
    cache: false
    mode: LEGACYHTML5

# 不限制文件上传的大小
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1


#微信小程序配置
wx:
  appId: wxeff6d2909bcea943
  appSecret: 65e16775e1739bfa15916cd1b267feda

#定时任务配置
scheduling:
  corePoolSize: 10
  maxPoolSize: 200
  queueCapacity: 10